# Enable debugging?
debug: false

# / - \ - / - \ - / - \ - / - \ - / - \
#
#         MINIGAME SUGGESTION
#    SoulStriker, check out his YT, https://www.youtube.com/channel/UCCCzzeKSOPipHb3tgQtekeA
# / - \ - / - \ - / - \ - / - \ - / - \

x-min: -300
z-min: -300
x-max: 300
z-max: 300
message: "&eA random crate was spawned in world &2{world} &eat &2{location}&e!"

# / - \ - / - \ - / - \ - / - \ - / - \
#
#           WORLD GENERATION
#
# / - \ - / - \ - / - \ - / - \ - / - \

# Enable randomly spawned crates around world?
generation: false

# Create any type of key for world name
# i do not recommend spawning in any world other than a world similar to the overworld (grass/trees/...)
# things just wont function as they should

# chance: chance to spawn a crate per newly generated chunk.
# chance ∈ [0, 100]
# so a chance of 2 will be a 2% chance to spawn in a new chunk
# - = - = - = WARNING = - = - = -
#  - setting the value for generation.<world>.chance to values higher values will increase lagg.
#    literally, setting the value to 75 will likely crash the server

# now, each crate chance is the chance for a certain crate
# common: 40 = 40%
# regular: 30 = 30%
# ultra: 15 = 15%
# rare: 10 = 10%
# legendary: 5 = 5%

# Enable "ruin" generation? Is purely aesthetic
ruin-generation: true

generation-settings:
  world:
    chance: 2 #Be careful with value; default
    crates:
      peasant: 75
      knight: 20
      king: 5
  #world_the_nether #not safely implemented
  #world_the_end #not safely implemented
  #other_worlds #not safely implemented


# Remove ruins on take?
remove-ruins: false

# / - \ - / - \ - / - \ - / - \ - / - \
#
#            TIMED SPAWNING
#   spawn crates randomly around the world?
# / - \ - / - \ - / - \ - / - \ - / - \

timed-spawn: false

timed-spawn-world: "world"

# in seconds
timed-spawn-min: 300
timed-spawn-max: 1200

# an optional message? make blank to disable ("")
timed-spawn-message: "&6A crate was spawned at {}"

# area is same as x-min/max/z above

# option to spawn a crate regarding the server tps, min must be met (0-20)
spawn-tps: 18