name: LootcratesExtended
main: com.crazicrafter1.lce.Main
version: 1.1.5
author: crazicrafter1
api-version: 1.13
depend: [LootCrates]
commands:
  lce:
    usage: /<command> <ruins | game>
    permission: lce.admin
permissions:
  lce.*:
    default: op
    children:
      - lce.admin
      - lce.cratespawn
  lce.admin:
    default: op
  lce.cratespawn:
    default: true

#prev: 1.0.2